### ISSUE TITLE
Stops working with HA core 2025.6 ⚠

### ISSUE THREAD

**Issue by tom-mi** [AlexanderLanin/homeassistant-sungrow#9]
The integration does not work anymore with `2025.6.0`:

```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 20:50:38 (1 occurrence)
Last logged: 20:50:38

Error setting up entry Sungrow Inverter Standalone for sungrow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sungrow/__init__.py", line 24, in async_setup_entry
    return await hass.config_entries.async_forward_entry_setup(entry, Platform.SENSOR)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```
I rolled back to HA core `2025.5.3` for now.
